### PR TITLE
generics test

### PR DESCRIPTION
**Pull request by Gmshruthi**

### CODE REVIEW

**Comment by Gmshruthi** [comment]
image
Generics-1.Create a generic class Box that can store any type of object and has methods to set and get the value.

**Comment by Gmshruthi** [comment]
Generics-1.Create a generic class Box that can store any type of object and has methods to set and get the value.
image

**Comment by Gmshruthi** [comment]
Write a generic method that prints an array of any type.
image

**Comment by Gmshruthi** [comment]
Generics-3.Create a generic method that accepts only numbers (e.g., Integer, Double, etc.) and returns the sum of two numbers.
image

**Comment by Gmshruthi** [comment]
Create a generic method that swaps two elements in an array.
image

**Comment by Gmshruthi** [comment]
Generics-5.Create a generic class Pair that can hold two values of any types (for example, a key-value pair).
image

**Review by Girubagarbalachandar — APPROVED** [review]

**Pull request merged**
